name: Dash User Contributions
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: 'macos-latest'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest
     - uses: actions/checkout@v2
     - run: >-
          wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz && tar -xzf
          docsetcontrib.tgz && ./docsetcontrib --verify | tee output.txt
     - uses: EliLillyCo/github-actions-post-to-pr@main
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        post_to_pr_definition: |
          [
            {
              "message_file": "./output.txt",
              "title": "Validation Results",
              "compare_branches": []
            }
          ]
